### ISSUE TITLE
Error Login CLEARTEXT communication

### ISSUE THREAD

**Issue by humansonofhuman** [TrejoCode/KristenAndroid#4]
CLEARTEXT communication to api.upqroo.edu.mx not permitted by network security policy

<details><summary>Captura de pantalla</summary>

![image](https://user-images.githubusercontent.com/18332876/51766813-82f27380-20a9-11e9-82b6-3fae380c583f.png)

</details>

---
[Video de como arreglarlo](https://youtu.be/nADShH87zVg) que encontró @TrejoCode  

---

**Comment by DiegoLovera** [comment]
Listo
