### ISSUE TITLE
Agregar leyenda de “No hay elementos” + carita de kristen

### ISSUE THREAD

**Issue by humansonofhuman** [TrejoCode/KristenAndroid#6]
![kristen](https://user-images.githubusercontent.com/18332876/51767480-8a1a8100-20ab-11e9-864f-c077aaf59fda.png)

En la página web se usa la leyenda:

---
#### Puedes aprovechar y alimentar a todos los perritos

---

**Comment by DiegoLovera** [comment]
Listo
